### PR TITLE
Rewriting node-webid in javascript and with tests

### PR DESCRIPTION
**Pull request by nicola**
**Attention: This is a breaking change since it supports a different callback style (the way it should be).**

This change does the following:

1. Different callback style
   ```
agent.verify(function(err, callback) { .. })
   ```
   instead of
   ```
agent.verify(function(success) { .. }, function(fail) { .. })
   ```

2. Removing coffee-script (all written in plain javascript)
3. Removed unused dependencies and updated the current ones (rdfstore has currently a bug that I reported https://github.com/antoniogarrote/rdfstore-js/issues/98 and fixed https://github.com/antoniogarrote/rdfstore-js/pull/99, however it is not merged yet, hence making the stability of this package questionable. We should implement it with `rdflib` instead)
4. Tests
5. Adding travis

### CODE REVIEW

**Comment by martinmr** [comment]
Looks good. We should probably wait a day or two to see if your PR gets accepted before merging. It won't be a lot of work for me to get it working on ldnode since the verify function is only used in one place.

**Comment by nicola** [comment]
Yes,
either that, or implementing this using rdflib.js

**Comment by nicola** [comment]
In case there are particular reasons for using rdfstore, I wrote the version using rdflib in #2

**Comment by nicola** [comment]
@martinmr, I rewrote that part using `rdflib` in #2,
please consider that PR unless we need rdfstore for a particular reason

**Pull request closed without merging**
