### PR TITLE
node-forge security issue

### PR DESCRIPTION
**Pull request by bourgeoa**
@RubenVerborgh

inrupt informed of a security issue in NSS due to node-forge <0.10.0 in node-webid
On Fri, Feb 5, 2021 at 10:36 PM David Bowen <david.bowen@inrupt.com> wrote:

    Hi Ruben and Jackson,

    Apologies for bringing this to you late on a Friday. I have been working out what to do with it.

    There is a known vulnerability in "node-forge":

    https://www.npmjs.com/advisories/1561

    which is consumed by "webid" and ultimately "node-solid-server":

    https://github.com/solid/node-solid-server/blob/fc2542bfaf54dbbb4e237ad47088169339d97700/package-lock.json#L11854

    I _believe_ it's showing in node-solid-server because the jump to 0.10.0 was incompatible so webid declaring an earlier version (0.7.4) is still resolving to 0.7.6 rather than jumping to 0.10.0 which we see in other packages that solid-server consumes.

    Davi recommended I contact you directly to let you know.

    Could you please update the dependency in webid?

    Thanks

I did not upgrade rdflib because even if all tests passes there is a logged error => xmldom error

```
  WebID
    TLS
      verifyKey
[xmldom error]	invalid doc source 
@#[line:0,col:undefined]
        ✓ should fail to verify unhandled profile mimeType-s
        ✓ should succeed on text/turtle
        ✓ should succeed on text/turtle; charset=utf-8
      verify
        ✓ valid certificate should have a uri as result (823ms)
        ✓ should reject a webID uri not found (479ms)
        ✓ should reject a certificate that does not match exponent or modulus (1208ms)
        ✓ should report certificateProvidedSAN if certificate is missing
        ✓ should report certificateProvidedSAN if certificate is empty
        ✓ should report missingModulus if only `URI:` is present (490ms)
      generate
        ✓ should create a valid certificate (114ms)


  10 passing (3s)

```

I suppose the problem lies in https://github.com/linkeddata/node-webid/blob/98b124ddc65193f3b395f6004cae3ad75f12bee1/lib/parse.js#L7, but did not find anything wrong in the code.

### CODE REVIEW

**Comment by bourgeoa** [comment]
@michielbdejong
can you add me to the repo ?
I propose to add lint and update to latest rdflib. This is what runs on NSS 5.6.4 (the console.log xmldom does no harm)
For solidos stack there is a PR https://github.com/solid/solidos/pull/31

**Review by michielbdejong — APPROVED** [review]
LGTM

**Comment by michielbdejong** [comment]
I also have no access to merge this.

@dmitrizagidulin you added us on https://www.npmjs.com/package/webid, can you add us as admins here on GitHub as well? Thanks a lot!!

**Comment by bourgeoa** [comment]
@RubenVerborgh can you add me to this github please.

**Pull request merged**
